### ISSUE TITLE
Develop TEM Simulator Wrapper

### ISSUE THREAD

**Issue by thisTyler** [compSPI/simSPI#10]
### Questions for wrapper

- Write utility functions in ioSPI allowing to go from one data format to another - utility functions that convert pdb to cif to 3d or accept all 3 ?
- Ask if classy?
- Ask configuration format? 
- seperate input file for pdb,cif?
- do we care about interim files?

### Notes

**Main functions**

Parameters:

TEMSimulator(inputfile,configuration_yaml,output_mrc=None,output_config=None) -> output: numpy data

Output:

TEMSimulator(inputfile,configuration_yaml) -> output : simulation object

simulation object

key/property : type
data: np array,
configuration: object,
write_mrc: function(output_file,config = true)

**Utility functions**

- generate_simulation_file_dirs(input_file, output_mrc,output_config) //(cryoemio.simio() but accepts all formats including cif,3d maps)
- fill_parameters_dictionary(yaml_file)
- fill_grid_in_fov(sample_dimensions, optics_params,detector_params, input_file=input_file,Dmax=30, pad=5.) 
                                        

**Work flow**

configurations -> 
define-grid (write crd file) -> 
build dictionary -> 
build input file from dictionary ->
run simulator ->
get mrc 

### transmission_electron.py | run
```
self.path_dict = self._getIOFilePaths(pdb_file)
self._buildCordFile(**self.path_dict, **self.sim_dict)
self.param_dict = self._build_param_dict(**self.path_dict, **self.sim_dict)
self._build_inpFile(self.param_dict, **self.path_dict)

data = self._getImageData(**self.filePaths)
```

### transmission_electron.py | get_image_data
```
SIMULATOR_BIN = Path(sim_path)  # might have to change depending on OS
inp_file = Path(path_dict["inp_file"])

cmd = "{0} {1}".format(SIMULATOR_BIN, inp_file)
os.system(shlex.quote(cmd))
```

**Comment by geoffwoollard** [comment]
`fill_grid_in_fov(sample_dimensions, optics_params,detector_params, input_file=input_file,Dmax=30, pad=5.)
` seems to be about simulating micrographs with multiple particles. Can temsim just simuate one particle in a small cropped region? Perhaps it can't and they will have to be "picked".

**Comment by ninamiolane** [comment]
What is the status on this? Should we close? @fredericpoitevin @geoffwoollard

**Comment by fredericpoitevin** [comment]
Yes, it might have been replaced by another one? Either way, it's not active anymore.
