### ISSUE TITLE
run tem simulator from docker image

### ISSUE THREAD

**Issue by geoffwoollard** [compSPI/simSPI#11]
See Fred's explanation about what a docker image is (in this PR https://github.com/compSPI/simSPI/pull/9) and how to run tem simulator from it.

So instead of calling a locally installed tem simuator, you would have it run from the container. This might take some extra steps with singularity, and making sure it's pointing to the container.

**Comment by ninamiolane** [comment]
I guess the steps for this issue/task would be:
- [ ] Ask @fredericpoitevin to add explanations in a README.md in the `simSPI/simSPI` repo about the docker image
- [ ] Follow @fredericpoitevin command lines, and:
  - [ ] Download the TEM "docker image" from the cloud
  - [ ] Create a container from the image
  - [ ] Enter the container and run code from the tem.py module
- [ ] Do the same things within the `.github/workflows/build.yml` to run tests about the tem simulator in the GitHub actions, using the docker image.

**Comment by fredericpoitevin** [comment]
Hi Team,

I wrote [this](https://github.com/compSPI/simSPI/blob/master/docker/README.md) to provide some context to the container approach. It's a little bit of a learning curve, so please let me know how you are doing and let me know where you have problems - even if at the very first step.

We can iterate until everyone manages to run TEM simulator :D

**Comment by geoffwoollard** [comment]
Suggested deadline: Jan 14
