### ISSUE TITLE
add white gaussian noise to clean tem simulator outputs

### ISSUE THREAD

**Issue by geoffwoollard** [compSPI/simSPI#34]
additive white gaussian noise adds is usually done after the ctf is included. the tem simulator gives clean ctf convoluted outputs, so we can add white gaussian noise on top and control exactly how much is added and how it is added.

 typically the noise is measured/reported with signal to noise ratio (SNR). this is defined as the variance of the signal divided by the variance of the noise (ie pure noise).

so if the output particle is `particle_2d`, then the variance would be `np.var(particle_2d)`. Note that the exact cropping changes what that number is, because the padding around the particle is constant, so having a lot of it reduces the variance of the signal.

the variance of the noise is just the variance of a "pure noise" image. With white gaussian noise this is `pure_noise = scale * np.random.normal(0,np.ones_like(particle_2d))`. Where scale is some float in R1. 

Because of iid noise of pixels in `np.random.normal(0,np.ones_like(particle_2d)`, and the additive and scale properties of normals (Var[ax] = a**2 Var[x]; N1[0,scale1] + N2[0,scale2] = N[0,sqrt(s1**2+s2**2)]) we get that `np.var(pure_noise)` is `scale` in expectation. You can just try this, make an image of pure noise of different sizes and you'll see that they have the same variance.

Thus
```
snr = np.var(particle_2d) / scale**2
```

There are other ways of reporting the noise. For instance, one could just report `scale` as above. Sometimes SNR is defined differently that above and the std is used instead of the var. And SNR can be in units of decibels (so -10 instead of 0.1 and -100 instead of 0.01).

I suggest you read in SNR from an input yaml, and then work backwards to what `scale` should be, and then add the noise in as `noisy = np.random.normal(particle_2d,scale)`.

For instance if there was 0.41SNR in an input file
* calculate the signal variance. Let's say it was to 0.4
* calculate the scale: scale =  sqrt(var(particle_2d) / snr) = sqrt(0.4/0.1 = sqrt(4) = 2
* add the noise to the particles: `noisy = np.random.normal(particle_2d,scale)`

I think it would be good to output the noisy and clean particles from the wrapper. In the competition, we can hold back things, but we're going to use this code to compute things, so let's have it output evaluate we need to evaluate.

**Comment by geoffwoollard** [comment]
also, when calculating the variance of the signal, you can average over batches of particles. each particle, depending on its orientation, will have a bit of a different variance. so average over the stack so it's orientation independent.

e.g. if particle one had var1=1 and particle 2 var2=1.1, then the variance to use would be 1.05 for both.

you can do this easily with passing in an index to `np.var(particle_2d_stack, axis=...).mean()`

**Comment by thisTyler** [comment]
Jumped on this and did a first pass at an implementation. Can be found in the gaussian_noise branches of ioSPI and simSPI (ioSPI only has some minor changes to the input files). 

The input files can either have a decibel or ratio value of SNR (the decibel takes priority), and if either are present then the wrapper automatically generates noisy .h5 files at the end in addition to the existing noiseless .h5 files. That is, when generating the final .h5 files we end up with a "~.h5" file and a "~-noisy.h5" file. 

Will have to touch base with the team regarding this before we press on with merges and such.

**Comment by geoffwoollard** [comment]
Suggested deadline: Jan 14

**Comment by arjunsingh3600** [comment]
Discussion from slack:

While reviewing the TEM simulator documentation, We found that the TEM simulator simulates detector blurring (using modulation transfer function) and detector quantum efficiency < 1. Currently, we are adding gaussian noise on top of the simulated particles instead of using these settings. Is the plan to keep it this way? why/ why not?

For now we want to not have any detector effects, ie perfect detector.
Why? Just to keep things simple.
Eventually on some future PR we would add that in. It’s a good example of “physics aware” where some analytical form of the forward model is known…
I think that’s why there was some params like [0 0 1 0] or something.

**Comment by jedyeo** [comment]
feature added in https://github.com/compSPI/simSPI/pull/43
