### ISSUE TITLE
`test_eval_ctf` fails for python 3.7

### ISSUE THREAD

**Issue by fredericpoitevin** [compSPI/simSPI#37]
PR #25 was merged but one test keeps failing due to an error elsewhere: https://github.com/compSPI/simSPI/runs/4485857206?check_suite_focus=true#step:7:43

The updated PR passes all the test except a test which is from TEM simulator and nothing to do with this PR. @geoffwoollard you might wanna look into it. The test function is written for a function which calls a random variable inside it. This is making it pass most of the times but fail a few times.

_Originally posted by @harshit-gupta-cor in https://github.com/compSPI/simSPI/issues/25#issuecomment-991112018_

**Comment by fredericpoitevin** [comment]
Actually, it looks like the error is due to `test_write_crd_file()`: https://github.com/compSPI/simSPI/runs/4502798979?check_suite_focus=true#step:7:23

Some closer look is needed.

**Comment by fredericpoitevin** [comment]
@harshit-gupta-cor could you please pinpoint the root cause? Thanks!

**Comment by harshit-gupta-cor** [comment]
`test_write_crd_file error()` is new to me. I was getting the following error: 

FAILED tests/test_transfer.py::test_eval_ctf - assert (99, 99) == (98, 98)

I am not sure what could be the exact reason but it looks like the shape that it asks for the CTF to make is missing by one pixel. This could be a [culprit](https://github.com/compSPI/simSPI/blob/9e389c8227ecca5aed98bb53bb400f83642d7c74/simSPI/transfer.py#L43). Seems like the test fails with some probability less than 1 so might also be stemming from some call to np.random.

**Comment by geoffwoollard** [comment]
I've seen this before and tried to track it down and reproduce... I thought I had fixed it. I'll look into it again

**Comment by geoffwoollard** [comment]
https://github.com/compSPI/simSPI/pull/12

**Comment by geoffwoollard** [comment]
Hmmm. It's passing tests. Let me check if its a random seed and try several times https://github.com/geoffwoollard/simSPI/runs/4512553889?check_suite_focus=true

**Comment by geoffwoollard** [comment]
Ok I solved that issue. PF with fix here: https://github.com/compSPI/simSPI/pull/40

**Comment by fredericpoitevin** [comment]
Great! Let me take a look at the PR now
