### ISSUE TITLE
Run TEM simulator tests in container.

### ISSUE THREAD

**Issue by fredericpoitevin** [compSPI/simSPI#48]
This workflow:
https://github.com/compSPI/simSPI/blob/master/.github/workflows/tem_dockerbuild.yml
builds the following container:
https://hub.docker.com/repository/docker/fpoitevi/simspi-temsimulator

Remains to be done:
run this workflow:
https://github.com/compSPI/simSPI/blob/master/.github/workflows/build.yml
in that container - also check path to executable in wrapper.

_Originally posted by @geoffwoollard in https://github.com/compSPI/simSPI/issues/47#issuecomment-995500784_

**Comment by fredericpoitevin** [comment]
**Little update**
This will require to build a *base* container with the conda environment in it, then built the TEM simulator container on top of it. Once that is done, tests within the TEM simulator container could be done with something like:
```python
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Install Singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Run tests in container
        run: singularity exec docker://${{ secrets.DOCKER_HUB_USERNAME }}/simspi-temsimulator:latest ...
```

**Comment by geoffwoollard** [comment]
Suggested PR deadline: Jan 10
