### ISSUE TITLE
Update Docker Image to Reflect ioSPI Refactoring

### ISSUE THREAD

**Issue by thisTyler** [compSPI/simSPI#75]
Because https://github.com/compSPI/simSPI/pull/65 is not merged, the TEM portion of simSPI is not functional. This PR is encountering import errors in which it does not recognize the refactoring changes to ioSPI (new library names are not found when we try to import them). 

I believe this is an issue with the docker image, please update it so that we can confirm tests pass and we can get this critical PR merged in ASAP.

**Comment by fredericpoitevin** [comment]
The Docker image has been updated with latest ioSPI but it does not seem to resolve things: https://github.com/compSPI/simSPI/runs/5300477112?check_suite_focus=true

**Comment by fredericpoitevin** [comment]
The error might not be related to the TEM simulator part, rather by a recent PR merged from the differentiable simulator side of things:
```==================================== ERRORS ====================================
_________________ ERROR collecting tests/test_params_utils.py __________________
ImportError while importing test module '/github/workspace/tests/test_params_utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/anaconda/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_params_utils.py:5: in <module>
    from simSPI.linear_simulator.params_utils import (
simSPI/linear_simulator/params_utils.py:8: in <module>
    from ioSPI.starfile import check_star_file, starfile_opticsparams
E   ModuleNotFoundError: No module named 'ioSPI.starfile'
```
Let me try to fix this.
