### ISSUE TITLE
TEM wrapper is not updated

### ISSUE THREAD

**Issue by luis-sribeiro** [compSPI/simSPI#78]
I was trying to use the TEM wrapper, but it has references to resources which are not available anymore (and weren't just renamed). For instance, while ``ioSPI.cryo.mrc2data`` has become ``ioSPI.micrographs.read_micrograph_from_mrc`` I was not able to find functionalities for creating the input file for the TEM Simulator.

**Comment by thisTyler** [comment]
Hi Luis - we currently have a PR that fixes this but it is blocked by https://github.com/compSPI/simSPI/issues/75, which Fred and I are working on. Sorry for the inconvenience!

**Comment by ninamiolane** [comment]
Thanks @thisTyler for the quick answer 🙌  let's keep this issue open until this is actually resolved. Thanks!
